POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpY2giLCJpZCI6IjVkNjcwNTQxYTAyZjJmMWRjOWIzZjFkZiIsImlhdCI6MTU2NzIxNDA4N30.yEgep9FYCf1PyONwu2jEdc7iOjk1s2IXM92rMFzf7mU

{
    "title": "Testing comments feature",
    "author": "Rich",
    "url": "me.org",
    "likes": 12,
    "userId": "5d670541a02f2f1dc9b3f1df"
}